### ISSUE TITLE
No password prompt when enabling script

### ISSUE THREAD

**Issue by logix2** [snyball/Hawck#13]
Using the latest Hawck from Git and Ubuntu 19.04 (with Gnome Shell), the password prompt is not shown when clicking the toggle button above the "Edit scripts" editor. I only get a notification saying "Require authentication as hawck-input", and this error in the terminal:

```
Installing script ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/hawck_ui-0.6-py3.7.egg/hawck_ui/window.py", line 676, in setScriptEnabled
    self.installScript(hwk_path)
  File "/usr/local/lib/python3.7/dist-packages/hawck_ui-0.6-py3.7.egg/hawck_ui/window.py", line 552, in installScript
    if not self.settings.unsafe_mode:
AttributeError: 'HawckMainWindow' object has no attribute 'settings'
```

**Comment by snyball** [comment]
Post the output of `ps aux | grep "[p]olkit" `

This might also be related to issue #12.

**Comment by snyball** [comment]
I'll try to install and run Hawck on Ubuntu 19.04, it might also be a library compatibility issue, I've only been testing Hawck on the 18.04 LTS. Seeing as you're running GNOME Shell you most likely have a `polkit` agent running, and if not that shouldn't produce this kind of error anyway.

**Comment by logix2** [comment]
```
$ ps aux | grep "[p]olkit"
root      1578  0.0  0.0 234448  9980 ?        Ssl  12:14   0:03 /usr/lib/policykit-1/polkitd --no-debug
```

**Comment by snyball** [comment]
Oh, it seems like your polkit agent isn't running for some reason. Try executing this:
```sh
$ /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
```

**Comment by logix2** [comment]
It says it's already running:

```
$ /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
** (polkit-gnome-authentication-agent-1:28828): WARNING **: 14:09:08.707: Unable to register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: An authentication agent already exists for the given subject
Cannot register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: An authentication agent already exists for the given subject
```

**Comment by snyball** [comment]
Ok, I see.

Are you able to get Hawck working on the 18.04 VM?
I'm asking because if it's not working on 18.04 then there has probably been an error during setup (and I'll have to clarify those in the FAQ.) If the 18.04 VM is working then there's probably a problem with Hawck.

**Comment by logix2** [comment]
It's still installing on the Ubuntu 18.04 VM... it takes a while as the vm is slow. Until then I noticed this:

```
The Meson build system
Version: 0.49.0
Source dir: /home/logix/Downloads/Hawck
Build dir: /home/logix/Downloads/Hawck/build
Build type: native build
Project name: Hawck
Project version: 0.6
Native C++ compiler: c++ (gcc 8.3.0 "c++ (Ubuntu 8.3.0-6ubuntu1) 8.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Found CMake: /usr/bin/cmake (3.13.4)
**Dependency lua found: NO (tried pkgconfig and cmake)**
Dependency lua5.3 found: YES 5.3.3
Dependency gtk+-3.0 found: YES 3.24.8
Dependency dbus-1 found: YES 1.12.12
Dependency gobject-2.0 found: YES 2.60.4
Dependency glib-2.0 found: YES 2.60.4
Dependency threads found: YES 
Dependency libnotify found: YES 0.7.7
Configuring hawck_config.h using configuration
**Dependency catch2 found: NO (tried pkgconfig and cmake)**
Message: Downloading Catch2 header file ...
DEPRECATION: Project targetting '>=0.45.0' but tried to use feature deprecated since '0.48.0': python3 module
Configuring setup_config.json using configuration
Program install-hawck-ui.sh found: YES (/home/logix/Downloads/Hawck/hawck-ui/install-hawck-ui.sh)
Program bin/hawck-setup.sh found: YES (/home/logix/Downloads/Hawck/bin/hawck-setup.sh)
```

I do have lua5.3 and liblua5.3-dev so I guess the forced includes of lua5.3 from meson.build needs to be customized for Ubuntu?

**Comment by logix2** [comment]
I tried it in the Ubuntu 18.04 vm and the exact same thing happens. The other bug https://github.com/snyball/Hawck/issues/12 is the same too.

**Comment by logix2** [comment]
The traceback looks different on Ubuntu 18.04, so here's the full hawck-ui log from Ubuntu 18.04:

```
$ hawck-ui

(hawck-ui:3091): Gtk-WARNING **: 13:24:19.054: Content added to the action area of a dialog using header bars

(hawck-ui:3091): Gtk-CRITICAL **: 13:24:19.057: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed
2750
2966
<hawck_ui.window.Settings object at 0x7f0c1e9e0cc0> autostart_switch False
<hawck_ui.window.Settings object at 0x7f0c1e9e0cc0> unsafe_mode_switch False
handler_name: on_notify_on_err_chk_toggled
Unable to retrieve config.stop_on_err
handler_name: on_eval_keydown_chk_toggled
handler_name: on_eval_keyup_chk_toggled
Unable to retrieve config.eval_keyrepeat
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 103, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 83, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler on_stop_on_err_chk_toggled not found
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 103, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 83, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler on_eval_keyrepeat_chk_toggled not found
Focus change: edit_scripts
Focus change: help
Focus change: settings
Focus change: simple_rebind
Focus change: simple_rebind
Focus change: status
Focus change: edit_scripts
Installing script ...
Output:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/hawck_ui-0.6-py3.6.egg/hawck_ui/window.py", line 676, in setScriptEnabled
    self.installScript(hwk_path)
  File "/usr/local/lib/python3.6/dist-packages/hawck_ui-0.6-py3.6.egg/hawck_ui/window.py", line 554, in installScript
    priv_actions.copyKeys(out.strip(), self.getCurrentScriptName())
  File "/usr/local/lib/python3.6/dist-packages/hawck_ui-0.6-py3.6.egg/hawck_ui/privesc.py", line 161, in sub
    return self.run(expl, user, fn, args)
  File "/usr/local/lib/python3.6/dist-packages/hawck_ui-0.6-py3.6.egg/hawck_ui/privesc.py", line 152, in run
    return callback_wrap(lambda exc, obj: obj)
  File "/usr/local/lib/python3.6/dist-packages/hawck_ui-0.6-py3.6.egg/hawck_ui/privesc.py", line 144, in callback_wrap
    exc, obj = json.loads(json_str)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Focus change: edit_scripts
```

**Comment by snyball** [comment]
Are you using the `install.sh` script? catch2 should be downloaded by a meson script if it isn't available. If you end up with an executable in the end I wouldn't think too much about the "lua: NO" thing, it has to be finding it somehow if it compiles.

You can disregard these errors:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 103, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 83, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler on_stop_on_err_chk_toggled not found
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 103, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 83, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler on_eval_keyrepeat_chk_toggled not found
```

These errors are interesting:
```
handler_name: on_notify_on_err_chk_toggled
Unable to retrieve config.stop_on_err
handler_name: on_eval_keydown_chk_toggled
handler_name: on_eval_keyup_chk_toggled
Unable to retrieve config.eval_keyrepeat
```
`hawck-ui` is retrieving these values from `hawck-macrod`, and can't initialize certain values on the settings tab if it can't communicate with `hawck-macrod`.

One thing you could try, to see if the polkit agent detection is broken (do this on your 19.04 install):
- Go to `hawck_ui/hawck_ui/privesc.py` line 180
- edit the `checkPkexec` function so that it looks like this:

```python
def checkPkexec():
    ## make return True the first statement
    return True
    ## Keep the rest of the code that follows
```

- Then, rebuild and reinstall `hawck-ui`

This error is probably caused by falling back to a dummy `echo` privesc method:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/hawck_ui-0.6-py3.6.egg/hawck_ui/window.py", line 676, in setScriptEnabled
    self.installScript(hwk_path)
  File "/usr/local/lib/python3.6/dist-packages/hawck_ui-0.6-py3.6.egg/hawck_ui/window.py", line 554, in installScript
    priv_actions.copyKeys(out.strip(), self.getCurrentScriptName())
  File "/usr/local/lib/python3.6/dist-packages/hawck_ui-0.6-py3.6.egg/hawck_ui/privesc.py", line 161, in sub
    return self.run(expl, user, fn, args)
  File "/usr/local/lib/python3.6/dist-packages/hawck_ui-0.6-py3.6.egg/hawck_ui/privesc.py", line 152, in run
    return callback_wrap(lambda exc, obj: obj)
  File "/usr/local/lib/python3.6/dist-packages/hawck_ui-0.6-py3.6.egg/hawck_ui/privesc.py", line 144, in callback_wrap
    exc, obj = json.loads(json_str)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
It's also possible that there's a new version of `pkexec` that is messing with the output, but try to see if it's just the detection of polkit that's broken by editing the source code.

**Comment by snyball** [comment]
`hawck-ui` should be updated to fail, displaying an error textbox, when it doesn't find an authentication agent, instead of the current dumb method of just falling back to "echo" (this is a placeholder for a more universal method, which I never found.)

**Comment by logix2** [comment]
Hi. Yes, I used the ``install.sh`` script. After editing ``privesc.py`` and rebuilding, I'm encountering the exact same issues on Ubuntu 19.04. 

On Ubuntu 18.04 though, after rebuilding, I did get an authentication prompt when turning the toggle to ON on the "Edit scripts" tab, and the script was enabled (simple rebinds still doesn't work), but only once, now if I turn it OFF, then ON, the prompt is not shown.

**Comment by snyball** [comment]
In the mean time, before I can figure out what the issue is, you can use the following workaround:

1. Edit your scripts with gedit/vim/nano or whatever else
2. Enable unsafe mode:
```
$ sudo cp hawck-master/bin/__UNSAFE_MODE.csv /var/lib/hawck-input/keys/
```
3. Use the `hwk2lua` command:
```
$ hwk2lua my_script.hwk > ~/.local/share/hawck/enabled-scripts/my_script.lua
$ chmod 744 ~/.local/share/hawck/enabled-scripts/my_script.lua
```
4. `journalctl | grep hawck` to look for errors
5. If you don't mind using Hawck without the `=>` operator you can now do
```
## When you save in your editor, hawck-macrod automatically reloads the script.
$ my-favorite-editor ~/.local/share/hawck/enabled-scripts/my_script.lua
```

This is essentially what Hawck UI does, except for the unsafe-mode part (or is supposed to do, at least.)

Have a nice weekend, I'll try reproducing it in a 19.04 VM now that I have some more time.

**Comment by snyball** [comment]
Closing this issue as I'm planning to deprecate the UI by version 1.0
